version: '2'
services:
  postgres:
    container_name: paymentdb
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=payment_provider
      - POSTGRES_PASSWORD=admin